language: python
python: 3.6

env:
  global:
    - SLUGIFY_USES_TEXT_UNIDECODE=yes

install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"

jobs:
  include:
    - stage: test
      before_script:
        - "airflow initdb"
        - "airflow connections --add --conn_id datadog_default --conn_type HTTP --conn_extr '{\"api_key\": \"\"}'"
      script:
        - "pytest -v"
    - stage: test
      script:
        - "pylint --disable=missing-docstring airflow_metrics"
        - "pylint --disable=missing-docstring --disable=too-few-public-methods --disable=no-self-use --disable=invalid-name tests"
